# System opengl 4.5
# Most up-to-date graphics card (intel/nvidia/amd) support opengl 4.5
# Even mesa 18.3.4 silently maybe support opengl 4.5 https://docs.mesa3d.org/relnotes/18.3.4.html
packages:
  all:
    providers:
      gl: [opengl, mesa+opengl]
      glx: [opengl, mesa+glx]
      glu: [openglu, mesa-glu]

  opengl:
    buildable: false
    externals:
    # $ glxinfo | grep 'OpenGL version string'
    - spec: opengl@4.5
      prefix: /usr
  openglu:
    buildable: false
    externals:
    - spec: openglu@1.3
      prefix: /usr
