# System opengl 4.5
# Most up-to-date graphics card (intel/nvidia/amd) support opengl 4.5
# Even mesa 18.3.4 silently maybe support opengl 4.5 https://docs.mesa3d.org/relnotes/18.3.4.html
packages:
  all:
    providers:
      # Spack 0.19:
      # - linux x11: gl(virt) is glx(bundle, shim) depends_on libglx(virt) is opengl(bundle, placeholder for external)
      # - mesa:      gl(virt) is osmesa(bundle, shim) depends_on libosmesa(virt) is mesa
      #              libglx(virt) is mesa

      # (allow fallback on mesa when explicit depends_on)
      gl:: [glx, osmesa]
      libglx:: [opengl, mesa+glx]
      glu:: [openglu, mesa-glu]
      libosmesa:: [mesa+osmesa]

  opengl:
    buildable: false
    externals:
    # $ glxinfo | grep 'OpenGL version string'
    - spec: opengl@4.5
      prefix: /usr
  openglu:
    buildable: false
    externals:
    - spec: openglu@1.3
      prefix: /usr
