#============== OS LAYER ==================
FROM ubuntu:22.04
#==========================================
# METADATA OF THE IMAGE
LABEL description "Test X11 and OGL" version="1.0" maintainer="Meshing team <lihpccg@gmail.com>"
#==========================================
#==========================================
SHELL ["/bin/bash", "-c"]
#==========================================
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#==========================================
RUN apt update &&\
    apt install -y x11-apps mesa-utils &&\
    apt clean &&\
    rm -rf /var/lib/apt/lists/*
