name: Check spec mgx

on:
  push:
    branches: 
      - main
    paths:
      - '**/package.py'
  pull_request:
    branches:
      - main
    paths:
      - '**/package.py'

jobs:
  Continuous:
    name: ${{ matrix.config }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Linux, Windows or Mac. 
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on:  ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2 # seems to be needed by codecov
        submodules: recursive

    - name: Initialize the environement
      shell: bash
      run: |
        git clone --depth=1 -b releases/latest https://github.com/spack/spack.git ${{github.workspace}}/spack
        source ${{github.workspace}}/spack/share/spack/setup-env.sh
        spack repo add ${{github.workspace}}/meshing
        spack repo add ${{github.workspace}}/meshing_supersede
    
    - name: Check Spack spec 
      # We create a subdirectory that will stand as our working directory for all 
      # subsequent commands
      run: |
        source ${{github.workspace}}/spack/share/spack/setup-env.sh
        spack spec mgx~smooth3d ^vtk-maillage~opengl2+qt ^qt+opengl
