name: Check push

on:
  [push, pull_request]

jobs:
  lint:
    name: Lint Recipes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Flake8 on meshing
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,F405,F403"
          path: "meshing"

      - name: Flake8 on meshing_supersede
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,F405,F403"
          path: "meshing_supersede"

  magix3d:
    name: Install Magix3D
    runs-on: ubuntu-latest
    needs: [lint]
    container:
      image: ghcr.io/lihpc-computational-geometry/spack-cgcore:latest
    strategy:
        fail-fast: false
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # seems to be needed by codecov
          submodules: recursive

      - name: Initialize Spack Environment
        shell: bash
        run: |
          source /spack/share/spack/setup-env.sh
          spack repo add $GITHUB_WORKSPACE/meshing
          spack repo add $GITHUB_WORKSPACE/meshing_supersede

      - name: Spack Install Magix3D
        shell: bash
        run: |
          source /spack/share/spack/setup-env.sh
          spack env activate meshing-env
          spack add magix3d~smooth3d~pythonaddon+doc ^vtk-maillage~opengl2+qt ^qt+opengl
          spack install -v --no-checksum
