name: Check mgx

on:
  push:
    branches: 
      - main
    paths:
      - '**/package.py'
  pull_request:
    branches:
      - main
    paths:
      - '**/package.py'

jobs:
  main:
    name: Check mgx
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lihpc-computational-geometry/spack-cgcore:latest

    steps:
      - name: Build and install
        shell: bash
        run: |
          source /spack/share/spack/setup-env.sh
          cd /spack_recipes && git pull
          spack repo add /spack_recipes/meshing
          spack repo add /spack_recipes/meshing_supersede
          spack env activate meshing-env
          spack add mgx~smooth3d^vtk-maillage~opengl2+qt
          spack add magix3d~smooth3d~pythonaddon+doc ^vtk-maillage~opengl2+qt ^qt+opengl
          spack install -v --no-checksum -v
