name: Check push

on:
  [push, pull_request]

jobs:
  lint-recipes:
    name: Lint Recipes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Flake8 on meshing
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,F405,F403"
          path: "meshing"

      - name: Flake8 on meshing_supersede
        uses: py-actions/flake8@v2
        with:
          ignore: "E501,F405,F403,W504"
          path: "meshing_supersede"

  spack-spec-mgx3d:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Linux, Windows or Mac.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Spack Spec Magix3D
    runs-on:  ubuntu-latest
    needs: [lint-recipes]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # seems to be needed by codecov
          submodules: recursive

      - name: Initialize Spack environment
        shell: bash
        run: |
          git clone --depth=1 -b releases/latest https://github.com/spack/spack.git ${{github.workspace}}/spack
          source ${{github.workspace}}/spack/share/spack/setup-env.sh
          spack repo add ${{github.workspace}}/meshing
          spack repo add ${{github.workspace}}/meshing_supersede

      - name: Check Spack spec
        # We create a subdirectory that will stand as our working directory for all
        # subsequent commands
        run: |
          source ${{github.workspace}}/spack/share/spack/setup-env.sh
          spack spec magix3d~smooth3d~pythonaddon+doc ^vtk-maillage~opengl2+qt ^qt+opengl

  spack-install-mgx3d:
    # Do not replace $GITHUB_WORKSPACE by ${{github.workspace}}
    # See https://github.com/actions/runner/issues/2058
    name: Spack Install Magix3D
    runs-on: ubuntu-latest
    needs: [spack-spec-mgx3d]
    container:
      image: ghcr.io/lihpc-computational-geometry/spack-cgcore:latest
    strategy:
        fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # seems to be needed by codecov
          submodules: recursive

      - name: Initialize Spack Environment
        shell: bash
        run: |
          source /spack/share/spack/setup-env.sh
          spack repo add $GITHUB_WORKSPACE/meshing
          spack repo add $GITHUB_WORKSPACE/meshing_supersede

      - name: Build and Install Magix3D
        shell: bash
        run: |
          source /spack/share/spack/setup-env.sh
          spack env activate meshing-env
          spack add magix3d~smooth3d~pythonaddon+doc ^vtk-maillage~opengl2+qt ^qt+opengl
          spack install -v --no-checksum
