name: Check mgx

on:
  push:
    branches: 
      - main
    paths:
      - 'package.py'
  pull_request:
    branches:
      - main
    paths:
      - 'package.py'

jobs:
  main:
    name: Check mgx
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lihpc-computational-geometry/spack-cgcore:latest

    steps:
      - name: Build and install
        shell: bash
        run: |
          cd /spack_recipes_meshing && git pull
          source /spack/share/spack/setup-env.sh
          spack env activate meshing-env
          spack add mgx~smooth3d^vtk-maillage~opengl2+qt
          spack install -v --no-checksum -v
