name: 'Create cmake-cgcore docker image'

on:
  push:
    tags:
      - 'cmake-cgcore-**'

env:
  REGISTRY: 'ghcr.io'
  USER_NAME: 'LIHPC-Computational-Geometry'
  DOCKERFILE_NAME: 'cmake-cgcore'

jobs:
  main:
    name: Create cmake-cgcore docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.USER_NAME }}/${{ env.DOCKERFILE_NAME }}
          labels: |
            org.opencontainers.image.title=lihpccg-cmake-cgcore
            org.opencontainers.image.vendor=CEA
          tags: |
            type=raw, latest
            type=raw, {{date 'YYYYMMDD'}}
            type=ref, event=tag

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
            file: ./dockerfiles/Dockerfile.${{ env.DOCKERFILE_NAME }}
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
