name: Make release

on:
  push:
    tags:
      - '*'

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest

    steps:
      # Checkout source files used by the Python checker
      - name: Checkout sources
        uses: actions/checkout@v3

      # Create a markdown file with Spack products and versions
      - name: List products and versions
        shell: bash
        run: |
          echo Project path: $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/.github/workflows && python list-versions.py $GITHUB_WORKSPACE

      # Create a Github Release
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
            body_path: $GITHUB_WORKSPACE/recipes.md
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
